### PR TITLE
Closes #2 AT+CWLAP, AT+CWLAPOPT and 'busy p...' fix

### LINKED ISSUE #2: AT command CWLAP
Hi, i have tested on ESP01S, i have sent a message to Telegram opening connection with AT+CIPSTART="SSL","api.telegram.org",443 and sent to chat id my message, all fine. :)

but maybe command for list of available network is not implemented? How to add it? 

Thank you for your job.

### PR DESCRIPTION
**Pull request by SamGeens**
Hi

I've pushed another PR, this time I implemented AT+CWLAP as asked for in issue #2 .

Things I did in this PR:

- Implemented AT+CWLAP
- Implemented AT+CWLAPOPT
- Changed busy to seperate boolean since it should not only be used for WiFi connecting state only
- readNumber can now also read negative numbers

Tested with commands and WiFiEsp library.

### CODE REVIEW

File: ESP_ATMod/ESP_ATMod.h [hunk 1]
```diff
@@ -84,7 +84,8 @@ extern bool gsEchoEnabled;		// command ATE
 extern uint8_t gsCipMux;		// command AT+CIPMUX
 extern uint8_t gsCipdInfo;		// command AT+CIPDINFO
 extern uint8_t gsCwDhcp;		// command AT+CWDHCP
-extern bool gsFlag_Connecting;	// Connecting in progress (CWJAP) - other commands ignored
+extern bool gsFlag_Connecting;	// Connecting in progress
```
Comment (JiriBilek) [inline ESP_ATMod/ESP_ATMod.h:87]: At a first glance I suspect, the `gsFlag_Connecting` and `gsFlag_Busy` are synonyms. If it is so, I'd be in favor to use `gsFlag_Busy` only.

**Review by JiriBilek — COMMENTED** [review]
Thanks again. I will check it out and test later today.

File: ESP_ATMod/command.cpp [hunk 2]
```diff
@@ -2662,3 +2748,146 @@ void printCertificateName(uint8_t number)
...
+
+/*
+ * Print the networks found from scanning
+ */
+void prinScanResult(int networksFound)
+{
+	if (sort_enable == 0)
+	{
+		size_t indices[networksFound];
+		for (size_t i = 0; i < networksFound; i++)
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:2871]: Here, `int` type should be used.

File: ESP_ATMod/command.cpp [hunk 3]
```diff
@@ -2662,3 +2748,146 @@ void printCertificateName(uint8_t number)
...
+			indices[i] = i;
+		}
+
+		// Print the unsorted networks
+		printCWLAP(indices, sizeof indices / sizeof *indices);
+	}
+	else if (sort_enable == 1)
+	{
+		size_t indices[networksFound];
+		for (size_t i = 0; i < networksFound; i++)
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:2882]: Here, `int` type should be used.

File: ESP_ATMod/command.cpp [hunk 4]
```diff
@@ -2559,6 +2638,13 @@ bool readNumber(unsigned char *inpBuf, uint16_t &offset, uint32_t &output)
 {
 	bool ret = false;
 	uint32_t out = 0;
+	size_t signNumber = 1;
+
+	if (inpBuf[offset] == '-')
+	{
+		signNumber = -1;
+		inpBuf[offset++];
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:2646]: no need to access the array. `++offset` should be used.

File: ESP_ATMod/command.cpp [hunk 5]
```diff
@@ -121,6 +122,17 @@ bool readNumber(unsigned char *inpBuf, uint16_t &offset, uint32_t &output);
...
+int compWifiRssi(const void *elem1, const void *elem2);
+void printCWLAP(int networksFound);
+void prinScanResult(int networksFound);
+
+/*
+ * Variables
+ */
+uint32_t sort_enable = 0;
+uint32_t printMask = 0x7FF;
+uint32_t rssiFilter = -100;
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:134]: When initializing with a negative value, signed type should be used: `int`

File: ESP_ATMod/command.cpp [hunk 6]
```diff
@@ -2559,6 +2638,13 @@ bool readNumber(unsigned char *inpBuf, uint16_t &offset, uint32_t &output)
 {
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:2638]: I understand you need to read negative numbers. But the output variable should be then `int32_t`. I don't know how this change affects the current code. There may jump dozens of unsigned/signed warnings. 
I'd prefer to detect the '-' in the only place where you read negative numbers (line 761) as mandatory character.

**Review by JiriBilek — CHANGES_REQUESTED** [review]
I found a couple of compilation warnings and `readNumber()` needs a fix.

File: ESP_ATMod/ESP_ATMod.h (hunk 1 above)
Comment (SamGeens) [reply ESP_ATMod/ESP_ATMod.h:87]: No they are not, `gsFlag_Connecting` is your function to check for a connecting. `gsFlagBusy`  is simply just letting the user/library know that the OS is busy. Which can be with connecting as used previously, but can also be with something else/other command. Like the CWLAP command now.

File: ESP_ATMod/command.cpp (hunk 2 above)
Comment (SamGeens) [reply ESP_ATMod/command.cpp:2871]: Resolved.

File: ESP_ATMod/command.cpp (hunk 5 above)
Comment (SamGeens) [reply ESP_ATMod/command.cpp:134]: Resolved.

File: ESP_ATMod/command.cpp (hunk 3 above)
Comment (SamGeens) [reply ESP_ATMod/command.cpp:2882]: Resolved.

File: ESP_ATMod/command.cpp (hunk 6 above)
Comment (SamGeens) [reply ESP_ATMod/command.cpp:2638]: Resolved.

File: ESP_ATMod/command.cpp [hunk 7]
```diff
@@ -2662,3 +2752,146 @@ void printCertificateName(uint8_t number)
...
+
+/*
+ * Print the networks found from scanning
+ */
+void prinScanResult(int networksFound)
+{
+	if (sort_enable == 0)
+	{
+		int indices[networksFound];
+		for (size_t i = 0; i < networksFound; i++)
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:2875]: The variable i should be `int`

File: ESP_ATMod/command.cpp [hunk 8]
```diff
@@ -2662,3 +2752,146 @@ void printCertificateName(uint8_t number)
...
+	}
+
+	gsFlag_Busy = false;
+	Serial.printf_P(MSG_OK);
+}
+
+/*
+ * Print the networks found from scanning
+ */
+void prinScanResult(int networksFound)
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:2870]: typo: `printScanResult`

File: ESP_ATMod/command.cpp [hunk 9]
```diff
@@ -2662,3 +2752,146 @@ void printCertificateName(uint8_t number)
...
+			indices[i] = i;
+		}
+
+		// Print the unsorted networks
+		printCWLAP(indices, sizeof indices / sizeof *indices);
+	}
+	else if (sort_enable == 1)
+	{
+		int indices[networksFound];
+		for (size_t i = 0; i < networksFound; i++)
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:2886]: the variable i should be `int`

File: ESP_ATMod/command.cpp [hunk 10]
```diff
@@ -2662,3 +2752,146 @@ void printCertificateName(uint8_t number)
...
+	if (sort_enable == 0)
+	{
+		int indices[networksFound];
+		for (size_t i = 0; i < networksFound; i++)
+		{
+			indices[i] = i;
+		}
+
+		// Print the unsorted networks
+		printCWLAP(indices, sizeof indices / sizeof *indices);
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:2881]: the size of indices array is `networkFound`, the expression `sizeof indices / sizeof *indices` seems to me to be correct by a coincidence only, because sizeof (*indices) == sizeof (int).

File: ESP_ATMod/command.cpp [hunk 11]
```diff
@@ -2662,3 +2752,146 @@ void printCertificateName(uint8_t number)
...
+	else if (sort_enable == 1)
+	{
+		int indices[networksFound];
+		for (size_t i = 0; i < networksFound; i++)
+		{
+			indices[i] = i;
+		}
+
+		// Sort by RSSI
+		qsort(indices, sizeof(indices) / sizeof(*indices), sizeof(*indices), compWifiRssi);
```
Comment (JiriBilek) [inline ESP_ATMod/command.cpp:2892]: I'd prefer more clear (although actually it's the same):
`qsort(indices, sizeof(indices) / sizeof(indices[0]), sizeof(indices[0]), compWifiRssi);`

**Review by JiriBilek — COMMENTED** [review]
The added feature works, the changes are minor due to compiler warning and simpler code.

File: ESP_ATMod/command.cpp (hunk 7 above)
Comment (SamGeens) [reply ESP_ATMod/command.cpp:2875]: Resolved.

File: ESP_ATMod/command.cpp (hunk 8 above)
Comment (SamGeens) [reply ESP_ATMod/command.cpp:2870]: Resolved.

File: ESP_ATMod/command.cpp (hunk 9 above)
Comment (SamGeens) [reply ESP_ATMod/command.cpp:2886]: Resolved.

Thank you for the information this will help.

File: ESP_ATMod/command.cpp (hunk 11 above)
Comment (SamGeens) [reply ESP_ATMod/command.cpp:2892]: Resolved.

File: ESP_ATMod/command.cpp (hunk 10 above)
Comment (SamGeens) [reply ESP_ATMod/command.cpp:2881]: That is true. I did this on purpose because I thought it is safer to actual check the length of the array instead of a number that should populate it. 

I suggest to keep it this way but I can change it to the same syntax you suggested in the next command:
`sizeof(indices) / sizeof(indices[0]), sizeof(indices[0])`

**Comment by SamGeens** [comment]
Normally I should be able to link this pull request to the issue by using the correct syntax in the title. Apparently I can't do it this time, could you link this PR to issue #2 ?

File: ESP_ATMod/command.cpp (hunk 10 above)
Comment (JiriBilek) [reply ESP_ATMod/command.cpp]: I know this is the same but for clarity please change it. The reason is I have seen many time the notation I suggested but never the yours one. Although they are the same.

Comment (JiriBilek) [reply ESP_ATMod/command.cpp]: You can see from my original comment, I was confused and initially thought the expression is wrong :)

**Comment by JiriBilek** [comment]
> 
> 
> Normally I should be able to link this pull request to the issue by using the correct syntax in the title. Apparently I can't do it this time, could you link this PR to issue #2 ?

Done.

**Comment by JiriBilek** [comment]
@SamGeens I noticed you are making your changes and the PR in your master branch. It is ok but be aware that until I merge the PR, everything you commit to your master will be added to the PR.
It's better to open a new branch for a PR and delete it after the PR is merged. Just an advise.

**Review by JiriBilek — COMMENTED** [review]
Looks good. Just please change the `sizeof(*indices)` to `sizeof(indices[0])`. There is one more occurence in the file (I didn't mark it)

**Comment by SamGeens** [comment]
> @SamGeens I noticed you are making your changes and the PR in your master branch. It is ok but be aware that until I merge the PR, everything you commit to your master will be added to the PR.
> It's better to open a new branch for a PR and delete it after the PR is merged. Just an advise.

I normally create a specific branch for the improvement I like to make, then merge it to master and then request a PR from master to your master branch. Every change you then request should be done on that branch so in this case it is my master branch. 

I'll do it from the specific branch in the future.

**Review by JiriBilek — APPROVED** [review]

**Comment by JiriBilek** [comment]
> 
> 
> > @SamGeens I noticed you are making your changes and the PR in your master branch. It is ok but be aware that until I merge the PR, everything you commit to your master will be added to the PR.
> > It's better to open a new branch for a PR and delete it after the PR is merged. Just an advise.
> 
> I normally create a specific branch for the improvement I like to make, then merge it to master and then request a PR from master to your master branch. Every change you then request should be done on that branch so in this case it is my master branch.
> 
> I'll do it from the specific branch in the future.

I mentioned it only because one day, I had made a PR from my master but the owner of the repo rejected it and I had problems with my cloned repo then.
